sudo: required
language: go

go:
  - "1.10.x"
  - "1.11.x"
  
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
script:
    - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build
    - ls
jobs:
  include:
    - stage: Build and push image
      services:
        - docker
      install: skip
      before_script:
        - make
      script:
        - docker build -t tomochain/proxy .
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag tomochain/proxy tomochain/proxy:latest
        - docker push tomochain/proxy:latest
        - docker tag tomochain/proxy tomochain/proxy:$TRAVIS_BUILD_ID
        - docker push tomochain/proxy:$TRAVIS_BUILD_ID
          
    - stage: Release application
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        overwrite: true
        on:
          tags: true

stages:
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = tomochain/proxy
  - name: Release application
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/proxy
